=== XilongPei/Openparts/Openparts-web/src/main/resources/query/query.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/query"
	xmlns:tns="http://www.example.org/query" elementFormDefault="qualified">
	<annotation>
		<documentation>
			Query Schema, created by billJiang in 盘锦 2015/1/16  modify in Beijing 2016/7/14
		</documentation>
	</annotation>
	<complexType name="callType">
		<sequence minOccurs="1"  maxOccurs="unbounded">
			<element name="call" minOccurs="1" maxOccurs="unbounded">
				<complexType>
					<sequence minOccurs="1" maxOccurs="1">
						<element name="param" maxOccurs=" 1" minOccurs="1" type="string" />
					</sequence>
					<attribute name="command" use="required" type="string"></attribute>
				</complexType>
			</element>
		</sequence>
	</complexType>
	<element name="queryContext">
		<complexType>
			<sequence>
				<element name="query" minOccurs="1" maxOccurs="unbounded">
					<complexType>
						<sequence>
							<element name="sql" type="string" maxOccurs="1" minOccurs="0" />
							<element name="varSql" type="string" maxOccurs="1" minOccurs="0" />
							<element name="beforeInit" maxOccurs="1" minOccurs="0"  type="tns:callType" />
							<element name="column" minOccurs="1" maxOccurs="unbounded">
								<complexType>
									<attribute name="key" use="required" type="string" />
									<attribute name="id" use="optional" type="string" />
									<attribute name="header" use="optional" type="string" />
									<attribute name="type" use="optional"  default="ro">
										<simpleType>
											<restriction base="string">
												<enumeration value="ro" />
												<enumeration value="link" />
												<enumeration value="ch" />
												<enumeration value="ra" />
												<enumeration value="ed" />
												<enumeration value="txt" />
												<enumeration value="coro" />
												<enumeration value="price" />
												<enumeration value="dyn" />
												<enumeration value="dhxCalendar"/>
											</restriction>
										</simpleType>
									</attribute>
									<attribute name="classType" use="optional"  default="java.lang.String">
										<simpleType>
											<restriction base="string">
												<enumeration value="java.lang.String" />
												<enumeration value="java.util.Date" />
												<enumeration value="java.lang.Integer" />
												<enumeration value="java.lang.Double" />
												<enumeration value="String" />
												<enumeration value="Date" />
												<enumeration value="Integer" />
												<enumeration value="Float" />
												<enumeration value="Double" />
												<enumeration value="BigDecimal" />
												<enumeration value="Boolean" />
											</restriction>
										</simpleType>
									</attribute>
									<attribute name="align"  default="center">
										<simpleType>
											<restriction base="string">
												<enumeration value="left" />
												<enumeration value="center" />
												<enumeration value="right" />
											</restriction>
										</simpleType>
									</attribute>
									<attribute name="allowSort" type="boolean" default="false"  />
								<!-- 	<attribute name="sortType"  default="str">
										<simpleType>
											<restriction base="string">
												<enumeration value="str" />
												<enumeration value="int" />
												<enumeration value="date" />
												<enumeration value="na" />
												<enumeration value="customSortFunction" />
											</restriction>
										</simpleType>
									</attribute> -->
									<attribute name="allowSearch" type="boolean" default="false" />
									<attribute name="hidden" type="boolean" default="false" />
									<attribute name="isQuote" type="boolean" default="true" />
									<attribute name="enableTooltip" type="boolean" default="true" />
									<attribute name="color" type="string" />
									<attribute name="operator"  default="eq">
										<simpleType>
											<restriction base="string">
												<enumeration value="eq" />
												<enumeration value="gt" />
												<enumeration value="ge" />
												<enumeration value="lt" />
												<enumeration value="le" />
												<enumeration value="in" />
												<enumeration value="not_in" />
												<enumeration value="between" />
												<enumeration value="like" />
												<enumeration value="not_eq" />
												<enumeration value="null" />
											</restriction>
										</simpleType>
									</attribute>
									<attribute name="width" type="string"  default="50" />
									<attribute name="dateFormat"  use="optional" default='yyyy-mm-dd'>
										<simpleType>
											<restriction base="string">
												<enumeration value="yyyy-mm-dd hh:ii:ss" />
												<enumeration value="yyyy-mm-dd hh:ii" />
												<enumeration value="yyyy-mm-dd hh" />
												<enumeration value="yyyy-mm-dd" />
												<enumeration value="yyyy-mm" />
												<enumeration value="yyyy.mm.dd hh:ii:ss" />
												<enumeration value="yyyy.mm.dd hh:ii" />
												<enumeration value="yyyy.mm.dd hh" />
												<enumeration value="yyyy.mm.dd" />
												<enumeration value="yyyy.mm" />
												<enumeration value="yyyy/mm/dd hh:ii:ss" />
												<enumeration value="yyyy/mm/dd hh:ii" />
												<enumeration value="yyyy/mm/dd hh" />
												<enumeration value="yyyy/mm/dd" />
												<enumeration value="yyyy/mm" />
												<enumeration value="yyyy" />
											</restriction>
										</simpleType>
									</attribute>
									<attribute name="numberFormat" type="string" use="optional" default="0,000.00" />
									<attribute name="fnRender" type="string" />
									<attribute name="isServerCondition" type="boolean" />
									<attribute name="value" type="string" />
									<attribute name="isExport" type="boolean" default="true" />
									<attribute name="isImport" type="boolean" default="false"/>
									<attribute name="suffix" type="string" default="%" />
									<attribute name="dict" type="string" />
									<attribute name="maxLen" type="int" />
									<attribute name="tooltip" type="string" />
									<attribute name="isJustExport" type="boolean" default="false" />
									<attribute name="render" type="string"/>
									<attribute name="subHeader"  default="#rspan">
										<simpleType>
											<restriction base="string">
												<enumeration value="#rspan" />
												<enumeration value="#select_filter_dict" />
												<enumeration value="#select_filter" />
												<enumeration value="#rspan" />
											</restriction>
										</simpleType>
									</attribute>
								</complexType> 
							</element>
							<element name="afterInit" maxOccurs="1" minOccurs="0" type="tns:callType" />
						</sequence> 
						<attribute name="id" type="string" use="required" />
						<attribute name="key" type="string" default="id" use="optional" />
						<attribute name="countStr" type="string" default="count(*)" />
						<attribute name="tableName"  use="required">
							<simpleType>
								<restriction base="string">
									<minLength value="4" />
								</restriction>
							</simpleType>
						</attribute>
						<attribute name="className" type="string" />
						<attribute name="pageSize" type="int" default="20" />
						<attribute name="pagesInGrp" type="int" default="5" />
						<attribute name="splitAt" type="int" use="optional" />
						<attribute name="widthType"  default="px" >
							<simpleType>
								<restriction base="string">
									<enumeration value="px"  />
									<enumeration value="%" />
								</restriction>
							</simpleType>
						</attribute>
						<attribute name="allowPaging" type="boolean" default="true" />
						<attribute name="filter" type="string" />
						<attribute name="order" type="string" />
						<attribute name="enableMultiline" type="boolean" default="true" />
						<attribute name="sortKey" type="string" />
						<attribute name="isServerFilter" type="boolean" default="false" />
						<attribute name="enableMultiHeader" type="boolean" default="false" />
						<attribute name="simpleSearch" type="string" default="true" />
						<attribute name="service" type="string" />
						<attribute name="method" type="string" />
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== XilongPei/Openparts/AdminEAP-web/src/main/resources/query/message.xml
<?xml version="1.0" encoding="UTF-8"?>
<queryContext xmlns="http://www.example.org/query" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.example.org/query query.xsd">
    <!--本xml片段为代码生成器生成，时间：2017-03-01 11:02:53-->
    <query id="message_list" key="id" tableName="消息列表" className="com.cnpc.tool.message.entity.Message" widthType="px">
        <column key="rowIndex" header="序号" width="80"/>
        <column key="sendUser" header="发送人" classType="String" allowSort="false" width="150"/>
        <column key="sendSubject" header="主题" classType="String" allowSort="true" width="150"/>
        <column key="sendContent" header="内容" classType="String" align="left" allowSort="false" width="150"/>
        <column key="sendTime" header="发送时间" classType="Date" allowSort="true" dateFormat="yyyy-mm-dd"  operator="between" width="150"/>
        <column key="messageType" header="消息类型" classType="String" allowSort="true" width="150"/>
        <column key="id" header="选择" classType="String" allowSort="false" width="150"/>
        <!-- <column key="messageStatus" header="消息状态" classType="String" allowSort="true" width="150"/>
         <column key="receiveUsers" header="接收人" hidden="true" classType="String" align="left" allowSort="false" width="150"/>
         <column key="messageFlag" header="消息标记" classType="String" allowSort="true" width="150"/>
         <column key="remark" header="备注" classType="String" align="left" allowSort="false" width="150"/>-->
    </query>
    <!-- 我的收件箱-->
    <query id="message_inbox" key="id" tableName="我的收件箱" className="com.cnpc.tool.message.entity.MessageReceiver" widthType="px">
        <column key="rowIndex" header="序号" width="80"/>
        <column key="message.sendUser" header="发送人" classType="String" allowSort="false" width="150"/>
        <column key="message.sendSubject" header="主题" enableTooltip="true" align="left" render="type=link,method=readMsg" classType="String" allowSort="true" width="150" fnRender="fnRenderSubject"/>
        <column key="message.sendTime" header="发送时间" classType="Date" allowSort="true"  dateFormat="yyyy-mm-dd hh:ii"  operator="between" width="150"/>
        <column key="messageType" header="类型" classType="String" align="left" width="50" fnRender="fnRenderMessageType"/>
        <column key="messageFlag" header="标记" classType="String"  allowSort="true" width="150" fnRender="fnRenderMessageFlag"/>
        <!--<column key="message.deleted" header="是否删除" classType="String" allowSort="true" width="150" render="0=可用,1=禁用"/>-->
        <column key="deleted" header="是否删除" hidden="true" classType="Integer" isServerCondition="true" value="0"/>
    </query>

    <!-- 我的回收站-->
    <query id="message_trash" key="id" tableName="我的回收站" className="com.cnpc.tool.message.entity.MessageReceiver" widthType="px">
        <column key="rowIndex" header="序号" width="80"/>
        <column key="message.sendUser" header="发送人" classType="String" allowSort="false" width="150"/>
        <column key="message.sendSubject" header="主题" enableTooltip="true" align="left" render="type=link,method=readMsg" classType="String" allowSort="true" width="150" fnRender="fnRenderSubject"/>
        <column key="message.sendTime" header="发送时间" classType="Date" allowSort="true"  dateFormat="yyyy-mm-dd hh:ii"  operator="between" width="150"/>
        <column key="messageType" header="类型" classType="String" align="left" width="50" fnRender="fnRenderMessageType"/>
        <column key="messageFlag" header="标记" classType="String" allowSort="true" width="150" fnRender="fnRenderMessageFlag"/>
        <!--<column key="message.deleted" header="是否删除" classType="String" allowSort="true" width="150" render="0=可用,1=禁用"/>-->
        <column key="deleted" header="是否删除" hidden="true" classType="Integer" isServerCondition="true" value="1"/>
    </query>


    <query id="message_sent" key="id" tableName="我的发件箱" className="com.cnpc.tool.message.entity.Message" widthType="px">
        <column key="rowIndex" header="序号" width="80"/>
        <column key="id" header="id" hidden="true"/>
        <column key="sendUser" header="发送人" hidden="true" classType="String" allowSort="false" width="150"/>
        <!--enableTootip(是否显示) maxLen(最大长度默认10，可在dataTables.js修改默认值) tooltip（指定tooltip来源，可不配，缺省为本身） 长文本鼠标悬停显示-->
        <!--弹窗方式render="type=window"使用;所需参数同modals.openWin的参数-->
        <!--<column key="sendSubject" header="主题" classType="String" align="left" render="type=window,winId=messageEditWin,url=/message/edit?id=[id],title=弹窗测试[sendSubject]" enableTooltip="true" maxLen="20" allowSort="true" width="150"/>-->
        <!--超链接方式 render="type=link",method方法名称，params方法参数,分号;分隔，如不需要参数params为可为空，默认注入rowId-->
        <!--<column key="sendSubject" header="主题" classType="String" align="left" render="type=link,method=loadPage,params='/message/edit?id=[id]';'#contentBody'" enableTooltip="true" maxLen="20" allowSort="true" width="150"/>-->
        <column key="sendSubject" header="主题" classType="String" align="left" render="type=link,method=showDetail" enableTooltip="true" maxLen="20" allowSort="true" width="150"/>
        <!--<column key="sendContent" header="内容" classType="String" align="left" allowSort="false" width="150" enableTooltip="true" maxLen="10"/>-->
        <column key="sendTime" header="发送时间" classType="Date" allowSort="true" dateFormat="yyyy-mm-dd hh:ii"  operator="between" width="150"/>
        <column key="messageType" header="类型" classType="String" align="left" width="50" fnRender="fnRenderMessageType"/>
        <column key="messageStatus" header="状态" classType="String" allowSort="false" width="50" fnRender="fnRenderMessageStatus"/>
        <column key="messageFlag" header="标记" classType="String" allowSort="true" width="150" fnRender="fnRenderMessageFlag"/>
        <column key="fileIds" header="附件" classType="String" width="150" fnRender="fnRenderFileIds"/>
         <!--<column key="receiveUsers" header="接收人" hidden="true" classType="String" align="left" allowSort="false" width="150"/>
         <column key="messageFlag" header="消息标记" classType="String" allowSort="true" width="150"/>
         <column key="remark" header="备注" classType="String" align="left" allowSort="false" width="150"/>-->
    </query>

    <!--草稿箱-->
    <query id="message_draft" key="id" tableName="我的草稿箱" className="com.cnpc.tool.message.entity.Message" widthType="px">
        <column key="rowIndex" header="序号" width="80"/>
        <column key="id" header="id" hidden="true"/>
        <column key="sendUser" header="发送人" hidden="true" classType="String" allowSort="false" width="150"/>
        <!--enableTootip(是否显示) maxLen(最大长度默认10，可在dataTables.js修改默认值) tooltip（指定tooltip来源，可不配，缺省为本身） 长文本鼠标悬停显示-->
        <!--弹窗方式render="type=window"使用;所需参数同modals.openWin的参数-->
        <!--<column key="sendSubject" header="主题" classType="String" align="left" render="type=window,winId=messageEditWin,url=/message/edit?id=[id],title=弹窗测试[sendSubject]" enableTooltip="true" maxLen="20" allowSort="true" width="150"/>-->
        <!--超链接方式 render="type=link",method方法名称，params方法参数,分号;分隔，如不需要参数params为可为空，默认注入rowId-->
        <!--<column key="sendSubject" header="主题" classType="String" align="left" render="type=link,method=loadPage,params='/message/edit?id=[id]';'#contentBody'" enableTooltip="true" maxLen="20" allowSort="true" width="150"/>-->
        <column key="sendSubject" header="主题" classType="String" align="left" render="type=link,method=showDetail" enableTooltip="true" maxLen="20" allowSort="true" width="150"/>
        <!--<column key="sendContent" header="内容" classType="String" align="left" allowSort="false" width="150" enableTooltip="true" maxLen="10"/>-->
        <column key="sendTime" header="发送时间" classType="Date" allowSort="true" dateFormat="yyyy-mm-dd hh:ii"  operator="between" width="150"/>
        <column key="messageType" header="类型" classType="String" align="left" width="50" fnRender="fnRenderMessageType"/>
        <!--isServerCondition=true value=0注入服务器端查询条件，也可在前端以type=hidden隐藏域的方式注入-->
        <column key="messageStatus" header="状态" isServerCondition="true" value="0" classType="String" allowSort="false" width="50" fnRender="fnRenderMessageStatus"/>
        <column key="messageFlag" header="标记" classType="String" allowSort="true" width="150" fnRender="fnRenderMessageFlag"/>
        <column key="fileIds" header="附件" classType="String" width="150" fnRender="fnRenderFileIds"/>
        <!--<column key="receiveUsers" header="接收人" hidden="true" classType="String" align="left" allowSort="false" width="150"/>
        <column key="messageFlag" header="消息标记" classType="String" allowSort="true" width="150"/>
        <column key="remark" header="备注" classType="String" align="left" allowSort="false" width="150"/>-->
    </query>

    <!--用户列表，选择消息接收人-->
    <query id="message_receiver_select_list" key="id" tableName="用户列表" className="com.cnpc.framework.base.entity.User"
           pageSize="10"  widthType="px" order="updateDateTime desc">
        <column key="isSelected" header="选择" fnRender="fnRenderSelectReceiver" />
        <column key="id" header="id" hidden="true" align="center" allowSort="false"/>
        <column key="rowIndex" header="序号" width="50" allowSort="false"/>
        <column key="version" header="version" hidden="true"/>
        <column key="name" header="姓名" operator="like" width="100" allowSort="true" />
        <column key="sex" header="性别" operator="eq" width="150" allowSort="true" render="1=男,0=女" />
        <column key="email" header="邮箱" align="left" operator="eq" width="100"  />
        <column key="mobile" header="手机"  operator="eq" width="200" align="center"/>
        <column key="qq" header="QQ" hidden="true" operator="eq" width="200" align="center" />
    </query>
</queryContext>
