=== XilongPei/Openparts/Openparts-web/src/main/resources/query/query.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/query"
	xmlns:tns="http://www.example.org/query" elementFormDefault="qualified">
	<annotation>
		<documentation>
			Query Schema, created by billJiang in 盘锦 2015/1/16  modify in Beijing 2016/7/14
		</documentation>
	</annotation>
	<complexType name="callType">
		<sequence minOccurs="1"  maxOccurs="unbounded">
			<element name="call" minOccurs="1" maxOccurs="unbounded">
				<complexType>
					<sequence minOccurs="1" maxOccurs="1">
						<element name="param" maxOccurs=" 1" minOccurs="1" type="string" />
					</sequence>
					<attribute name="command" use="required" type="string"></attribute>
				</complexType>
			</element>
		</sequence>
	</complexType>
	<element name="queryContext">
		<complexType>
			<sequence>
				<element name="query" minOccurs="1" maxOccurs="unbounded">
					<complexType>
						<sequence>
							<element name="sql" type="string" maxOccurs="1" minOccurs="0" />
							<element name="varSql" type="string" maxOccurs="1" minOccurs="0" />
							<element name="beforeInit" maxOccurs="1" minOccurs="0"  type="tns:callType" />
							<element name="column" minOccurs="1" maxOccurs="unbounded">
								<complexType>
									<attribute name="key" use="required" type="string" />
									<attribute name="id" use="optional" type="string" />
									<attribute name="header" use="optional" type="string" />
									<attribute name="type" use="optional"  default="ro">
										<simpleType>
											<restriction base="string">
												<enumeration value="ro" />
												<enumeration value="link" />
												<enumeration value="ch" />
												<enumeration value="ra" />
												<enumeration value="ed" />
												<enumeration value="txt" />
												<enumeration value="coro" />
												<enumeration value="price" />
												<enumeration value="dyn" />
												<enumeration value="dhxCalendar"/>
											</restriction>
										</simpleType>
									</attribute>
									<attribute name="classType" use="optional"  default="java.lang.String">
										<simpleType>
											<restriction base="string">
												<enumeration value="java.lang.String" />
												<enumeration value="java.util.Date" />
												<enumeration value="java.lang.Integer" />
												<enumeration value="java.lang.Double" />
												<enumeration value="String" />
												<enumeration value="Date" />
												<enumeration value="Integer" />
												<enumeration value="Float" />
												<enumeration value="Double" />
												<enumeration value="BigDecimal" />
												<enumeration value="Boolean" />
											</restriction>
										</simpleType>
									</attribute>
									<attribute name="align"  default="center">
										<simpleType>
											<restriction base="string">
												<enumeration value="left" />
												<enumeration value="center" />
												<enumeration value="right" />
											</restriction>
										</simpleType>
									</attribute>
									<attribute name="allowSort" type="boolean" default="false"  />
								<!-- 	<attribute name="sortType"  default="str">
										<simpleType>
											<restriction base="string">
												<enumeration value="str" />
												<enumeration value="int" />
												<enumeration value="date" />
												<enumeration value="na" />
												<enumeration value="customSortFunction" />
											</restriction>
										</simpleType>
									</attribute> -->
									<attribute name="allowSearch" type="boolean" default="false" />
									<attribute name="hidden" type="boolean" default="false" />
									<attribute name="isQuote" type="boolean" default="true" />
									<attribute name="enableTooltip" type="boolean" default="true" />
									<attribute name="color" type="string" />
									<attribute name="operator"  default="eq">
										<simpleType>
											<restriction base="string">
												<enumeration value="eq" />
												<enumeration value="gt" />
												<enumeration value="ge" />
												<enumeration value="lt" />
												<enumeration value="le" />
												<enumeration value="in" />
												<enumeration value="not_in" />
												<enumeration value="between" />
												<enumeration value="like" />
												<enumeration value="not_eq" />
												<enumeration value="null" />
											</restriction>
										</simpleType>
									</attribute>
									<attribute name="width" type="string"  default="50" />
									<attribute name="dateFormat"  use="optional" default='yyyy-mm-dd'>
										<simpleType>
											<restriction base="string">
												<enumeration value="yyyy-mm-dd hh:ii:ss" />
												<enumeration value="yyyy-mm-dd hh:ii" />
												<enumeration value="yyyy-mm-dd hh" />
												<enumeration value="yyyy-mm-dd" />
												<enumeration value="yyyy-mm" />
												<enumeration value="yyyy.mm.dd hh:ii:ss" />
												<enumeration value="yyyy.mm.dd hh:ii" />
												<enumeration value="yyyy.mm.dd hh" />
												<enumeration value="yyyy.mm.dd" />
												<enumeration value="yyyy.mm" />
												<enumeration value="yyyy/mm/dd hh:ii:ss" />
												<enumeration value="yyyy/mm/dd hh:ii" />
												<enumeration value="yyyy/mm/dd hh" />
												<enumeration value="yyyy/mm/dd" />
												<enumeration value="yyyy/mm" />
												<enumeration value="yyyy" />
											</restriction>
										</simpleType>
									</attribute>
									<attribute name="numberFormat" type="string" use="optional" default="0,000.00" />
									<attribute name="fnRender" type="string" />
									<attribute name="isServerCondition" type="boolean" />
									<attribute name="value" type="string" />
									<attribute name="isExport" type="boolean" default="true" />
									<attribute name="isImport" type="boolean" default="false"/>
									<attribute name="suffix" type="string" default="%" />
									<attribute name="dict" type="string" />
									<attribute name="maxLen" type="int" />
									<attribute name="tooltip" type="string" />
									<attribute name="isJustExport" type="boolean" default="false" />
									<attribute name="render" type="string"/>
									<attribute name="subHeader"  default="#rspan">
										<simpleType>
											<restriction base="string">
												<enumeration value="#rspan" />
												<enumeration value="#select_filter_dict" />
												<enumeration value="#select_filter" />
												<enumeration value="#rspan" />
											</restriction>
										</simpleType>
									</attribute>
								</complexType> 
							</element>
							<element name="afterInit" maxOccurs="1" minOccurs="0" type="tns:callType" />
						</sequence> 
						<attribute name="id" type="string" use="required" />
						<attribute name="key" type="string" default="id" use="optional" />
						<attribute name="countStr" type="string" default="count(*)" />
						<attribute name="tableName"  use="required">
							<simpleType>
								<restriction base="string">
									<minLength value="4" />
								</restriction>
							</simpleType>
						</attribute>
						<attribute name="className" type="string" />
						<attribute name="pageSize" type="int" default="20" />
						<attribute name="pagesInGrp" type="int" default="5" />
						<attribute name="splitAt" type="int" use="optional" />
						<attribute name="widthType"  default="px" >
							<simpleType>
								<restriction base="string">
									<enumeration value="px"  />
									<enumeration value="%" />
								</restriction>
							</simpleType>
						</attribute>
						<attribute name="allowPaging" type="boolean" default="true" />
						<attribute name="filter" type="string" />
						<attribute name="order" type="string" />
						<attribute name="enableMultiline" type="boolean" default="true" />
						<attribute name="sortKey" type="string" />
						<attribute name="isServerFilter" type="boolean" default="false" />
						<attribute name="enableMultiHeader" type="boolean" default="false" />
						<attribute name="simpleSearch" type="string" default="true" />
						<attribute name="service" type="string" />
						<attribute name="method" type="string" />
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== XilongPei/Openparts/AdminEAP-web/src/main/resources/query/tool.xml
<?xml version="1.0" encoding="UTF-8"?>
<queryContext xmlns="http://www.example.org/query" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/query query.xsd ">
	<!-- 文章列表 -->
	<query id="markdown_list" key="id" tableName="文章列表" className="com.cnpc.tool.markdown.entity.MarkDown"
		pageSize="10"  widthType="px" order="updateDateTime desc">
		<column key="rowIndex" header="序号" width="50" allowSort="false"/>
		<column key="id" header="id" hidden="true"/>
		<column key="version" header="version" hidden="true"/>
		<column key="title" header="文章标题" align="left" operator="like" width="100" allowSort="true" />
		<column key="keywords" header="关键字" align="left" operator="eq" width="150" />
	    <column key="operator" id="id" header="操作" align="center" fnRender="fnRenderOperator"/>
	</query>

	<query id="job_list" key="jobId" tableName="计划中的任务" widthType="px"  allowPaging="false" simpleSearch="false" service="jobService" method="getAllJobs" className="com.cnpc.framework.base.pojo.ScheduleJob">
		<column key="rowIndex" header="序号" width="70" />
		<column key="jobId" header="任务id" operator="eq" hidden="true" width="100"/>
		<column key="jobName" header="任务名" width="100" />
		<column key="jobGroup" header="任务组"  width="100" />
		<column key="triggerName" header="trigger名"  width="100" />
		<column key="triggerGroup" header="trigger组" width="100" />
		<column key="triggerType" header="trigger类型" width="100"/>
		<column key="jobStatus" header="任务状态" width="100" />
		<column key="jobClass" header="执行类名" width="300" align="left"/>
		<column key="cronExpression" header="cron表达式" width="100" />
		<column key="startTime" classType="java.util.Date"  header="开始时间" dateFormat="yyyy-mm-dd hh:ii" width="150"/>
		<column key="endTime" classType="java.util.Date" header="结束时间" dateFormat="yyyy-mm-dd hh:ii" width="150"/>
		<column key="repeatType"  header="重复类型" width="200"/>
		<column key="repeatCount" classType="java.lang.Integer" header="重复次数" width="70"/>
		<column key="repeatIntervalStr"  header="时间间隔" width="100"/>
		<column key="desc" header="备注" width="300" align="left" />
	</query>
</queryContext>

=== XilongPei/Openparts/Openparts-web/src/main/resources/query/base.xml
<?xml version="1.0" encoding="UTF-8"?>
<queryContext xmlns="http://www.example.org/query" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/query query.xsd ">
	<!-- 用户列表 -->
	<query id="user_list" key="id" tableName="用户列表" className="com.cnpc.framework.base.entity.User"
		pageSize="10"  widthType="px" order="id asc">
		<column key="rowIndex" header="序号" width="50" allowSort="false"/>
		<column key="id" header="id" hidden="true"/>
		<column key="version" header="version" hidden="true"/>
		<column key="name" header="姓名" operator="like" width="100" allowSort="true" />
		<column key="deptId" header="所在部门" align="left" width="100" fnRender="fnRenderDept"/>
		<column key="sex" header="性别" operator="eq" width="150" allowSort="true" render="1=男,0=女" />
		<column key="birthday" header="出生年月" operator="like" width="80" allowSort="true" dateFormat="yyyy-mm-dd" />
		<column key="loginName" header="登录名" operator="like" width="80" allowSort="true" />
		<column key="email" header="邮箱" align="left" operator="eq" width="100"  />
		<column key="mobile" header="手机" operator="eq" width="200" align="center"/>
	    <column key="qq" header="QQ" operator="eq" width="200" align="center" />
	</query>
	
	<!-- 角色列表 -->
	<query id="role_list" key="id" tableName="角色列表" className="com.cnpc.framework.base.entity.Role"
		pageSize="10"  widthType="px" order="sort asc" allowPaging="false">
		<column key="rowIndex" header="序号" width="50" allowSort="false"/>
		<column key="id" header="id" hidden="true"/> 
		<column key="version" header="version" hidden="true"/>
		<column key="name" header="名称" operator="like" width="100" allowSort="true" />
		<column key="code" header="编码" operator="eq" width="100" allowSort="true"/>
		<column key="deleted" header="是否可用" width="80" allowSort="true" render="1=禁用,0=可用" />
		<column key="remark" header="备注" width="100" allowSort="false" /> 
	</query>
	
	<!-- 角色用户列表  已经绑定该角色的用户 -->
    <query id="userRole_selected_list" key="id" tableName="角色用户列表（已绑定）" className="com.cnpc.framework.base.entity.UserRole"
		pageSize="10"  widthType="px" order="updateDateTime desc" allowPaging="true">
		<column key="rowIndex" header="序号" width="50" allowSort="false"/>
		<column key="id" header="id" hidden="true"/>
		<column key="version" header="version" hidden="true"/>
		<column key="roleId"  header="roleId" operator="eq"  hidden="true"/>
		<column key="user.name" header="用户名" operator="like" width="100" allowSort="true" />
		<column key="user.loginName" header="登录名" operator="eq" width="100" allowSort="true"/>
	</query>

	<!-- 角色授权列表  已经绑定该角色的权限列表 -->
	<query id="roleFunc_selected_list" key="id" tableName="角色功能列表（已绑定）"  pageSize="10"  widthType="px" order="f.levelCode desc" allowPaging="false">
		<sql>
			<![CDATA[
			  select rf.id id,rf.version version,rf.roleId roleId,f.name name,p.name pname,
			  f.code code from tbl_role_function rf
			  left join tbl_function f on rf.functionId=f.id
			  left join tbl_function p on f.parent_id=p.id
			  where 1=1 and f.functype!='0'
			]]>
		</sql>
		<column key="rowIndex" header="序号" width="50" allowSort="false"/>
		<column key="id" header="id" hidden="true"/>
		<column key="version" header="version" hidden="true"/>
		<column key="roleId"  header="roleId" operator="eq"  hidden="true"/>
		<column key="name" header="功能名" operator="like" width="100" align="left" allowSort="true" />
		<column key="code" header="功能编码" operator="eq" width="100" allowSort="true"/>
		<column key="pname" header="父功能" operator="eq" width="100" allowSort="true" align="left"/>
	</query>

	<!--功能数据权限-->
	<query id="ff_list" key="id" tableName="功能数据权限列表"  pageSize="10"  widthType="px" order="sort asc" allowPaging="false" className="com.cnpc.framework.base.entity.FunctionFilter">
		<column key="rowIndex" header="序号" width="50" allowSort="false"/>
		<column key="id" header="id" hidden="true"/>
		<column key="version" header="version" hidden="true"/>
		<column key="roleId" header="roleId" hidden="true" operator="eq"/>
		<column key="functionId" header="functionId" hidden="true" operator="eq"/>
		<column key="key" header="条件" operator="like" width="100" allowSort="true" />
		<column key="operator" header="操作符" operator="like" width="100" allowSort="true" />
		<column key="value" header="值" operator="like" width="100" allowSort="true" />
		<column key="classType" header="类型" operator="eq" width="100" allowSort="true"/>
	</query>

	<!-- 未绑定角色的用户 -->
	<query id="userRole_unselected_list" key="id" tableName="角色用户列表（未绑定）" pageSize="10"  widthType="px"  allowPaging="true">
       <sql>   
	      <![CDATA[   
	      select id,version,name,login_name from tbl_user where 
	      id not in (select userId from tbl_user_role where roleId=@roleId#)
          and 1=1 
          order by update_date_time desc
	      ]]>
	    </sql>
		<column key="rowIndex" header="序号" width="50" allowSort="false"/>
		<column key="id" header="id" hidden="true"/>
		<column key="version" header="version" hidden="true"/>
		<column key="name" header="用户名" operator="like" width="100" allowSort="true" />
		<column key="login_name" header="登录名" operator="eq" width="100" allowSort="true"/>
	</query>

	<!--通用用户选择-->
	<query id="user_select_list" key="id" tableName="用户选择" className="com.cnpc.framework.base.entity.User"
		   pageSize="10"  widthType="px" order="updateDateTime desc">
		<column key="isSelected" header="选择" fnRender="fnRenderSelectUser" />
		<column key="id" header="id" hidden="true" align="center" allowSort="false"/>
		<column key="rowIndex" header="序号" width="50" allowSort="false"/>
		<column key="version" header="version" hidden="true"/>
		<column key="name" header="姓名" operator="like" width="100" allowSort="true" />
		<column key="sex" header="性别" operator="eq" width="150" allowSort="true" render="1=男,0=女" />
		<column key="email" header="邮箱" align="left" operator="eq" width="100"  />
		<column key="mobile" header="手机"  operator="eq" width="200" align="center"/>
		<column key="qq" header="QQ" hidden="true" operator="eq" width="200" align="center" />
	</query>
</queryContext>

=== XilongPei/Openparts/AdminEAP-web/src/main/resources/query/activiti-demo.xml
<?xml version="1.0" encoding="UTF-8"?>
<queryContext xmlns="http://www.example.org/query" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.example.org/query query.xsd">
    <!--本xml片段为代码生成器生成，时间：2017-07-05 20:13:35-->
    <query id="train_list" key="id" tableName="培训选课列表" className="com.cnpc.activiti.entity.Train" widthType="px">
        <column key="rowIndex" header="序号" width="80"/>
        <column key="name" header="课程名称" classType="String" allowSort="true" width="150"/>
        <column key="courseTime" header="上课时间" classType="String" allowSort="true" width="150"/>
        <column key="duration" header="课时" classType="Integer" allowSort="true" width="150"/>
        <column key="teacher" header="上课老师" classType="String" allowSort="true" width="150"/>
        <column key="address" header="地点" classType="String" allowSort="true" width="150"/>
        <column key="remark" header="备注" classType="String" align="left" allowSort="false" width="150"/>
        <column key="state" header="流程状态" fnRender="fnRenderState"/>
        <column key="id" header="操作" fnRender="fnRenderOperation"/>
    </query>
</queryContext>

=== XilongPei/Openparts/Openparts-web/src/main/resources/query/demos.xml
<?xml version="1.0" encoding="UTF-8"?>
<queryContext xmlns="http://www.example.org/query" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.example.org/query query.xsd">
    <!--本xml片段为代码生成器生成，时间：2017-02-10 11:44:41-->
    <query id="generator" key="id" tableName="测试列表" className="com.cnpc.demos.entity.Generator" widthType="px">
        <column key="rowIndex" header="序号" width="80"/>
        <column key="name" header="姓名" width="150" operator="like" allowSort="true"/>
        <column key="code" header="编码" width="150"/>
        <column key="gender" header="性别" width="150"/>
        <column key="birthday" header="生日" classType="java.util.Date" operator="between" width="150" dateFormat="yyyy-mm-dd"/>
        <column key="nation.name" header="民族" width="150"/>
        <column key="education" header="学历" width="150"/>
        <column key="salary" header="工资" width="150"/>
        <column key="department" header="所在组织" width="150"/>
        <column key="remark" header="备注" align="left" width="150"/>
        <column key="enable" header="是否启用" width="150"/>
    </query>
</queryContext>

=== XilongPei/Openparts/Openparts-web/src/main/resources/query/openparts.xml
<?xml version="1.0" encoding="UTF-8"?>
<queryContext xmlns="http://www.example.org/query" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/query query.xsd">
<!--本xml片段为代码生成器生成，时间：2017-11-17 12:45:48-->
<query id="whisper_nodes" key="id" tableName="whisper_nodes列表" className="com.openparts.base.entity.Whisper_nodes" widthType="px">
        <column key="rowIndex" header="序号" width="80"/>
        <column key="name" header="name" classType="String" allowSort="true" width="150"/>
        <column key="description" header="description" classType="String" allowSort="true" width="150"/>
        <column key="version" header="version" classType="String" allowSort="true" width="150"/>
        <column key="device_id" header="device_id" classType="String" allowSort="true" width="150"/>
        <column key="real_device_id" header="real_device_id" classType="String" allowSort="true" width="150"/>
        <column key="device_type" header="device_type" classType="String" allowSort="true" width="150"/>
        <column key="manufacturer" header="manufacturer" classType="String" allowSort="true" width="150"/>
        <column key="model" header="model" classType="String" allowSort="true" width="150"/>
        <column key="os" header="os" classType="String" allowSort="true" width="150"/>
        <column key="os_version" header="os_version" classType="String" allowSort="true" width="150"/>
</query>
</queryContext>
